server:
    address: monkeyhorse.cn
    port: 80
    contextPath:

spring:
    profiles:
        active: production

    thymeleaf:
        cache: true

    jade4j:
        caching: true

    dataSource:
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1/monkeyhorse
      username: root
      password: root

    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect
      hbm2ddl.auto: update
      show_sql: false

    redis:
      host: localhost
      port: 6379
      default_expire_time: 86400

